
import { BibleBook, Testament } from './types';

// Weights based on approximate English word counts (ESV/KJV averages)
export const BIBLE_BOOKS: BibleBook[] = [
  { id: 'gen', name: 'Genesis', testament: Testament.OLD, wordCount: 38267, chapters: 50 },
  { id: 'exo', name: 'Exodus', testament: Testament.OLD, wordCount: 32035, chapters: 40 },
  { id: 'lev', name: 'Leviticus', testament: Testament.OLD, wordCount: 24546, chapters: 27 },
  { id: 'num', name: 'Numbers', testament: Testament.OLD, wordCount: 32333, chapters: 36 },
  { id: 'deu', name: 'Deuteronomy', testament: Testament.OLD, wordCount: 28461, chapters: 34 },
  { id: 'jos', name: 'Joshua', testament: Testament.OLD, wordCount: 18858, chapters: 24 },
  { id: 'jud', name: 'Judges', testament: Testament.OLD, wordCount: 18976, chapters: 21 },
  { id: 'rut', name: 'Ruth', testament: Testament.OLD, wordCount: 2578, chapters: 4 },
  { id: '1sa', name: '1 Samuel', testament: Testament.OLD, wordCount: 25061, chapters: 31 },
  { id: '2sa', name: '2 Samuel', testament: Testament.OLD, wordCount: 20614, chapters: 24 },
  { id: '1ki', name: '1 Kings', testament: Testament.OLD, wordCount: 24524, chapters: 22 },
  { id: '2ki', name: '2 Kings', testament: Testament.OLD, wordCount: 23532, chapters: 25 },
  { id: '1ch', name: '1 Chronicles', testament: Testament.OLD, wordCount: 20369, chapters: 29 },
  { id: '2ch', name: '2 Chronicles', testament: Testament.OLD, wordCount: 26074, chapters: 36 },
  { id: 'ezr', name: 'Ezra', testament: Testament.OLD, wordCount: 7440, chapters: 10 },
  { id: 'neh', name: 'Nehemiah', testament: Testament.OLD, wordCount: 10483, chapters: 13 },
  { id: 'est', name: 'Esther', testament: Testament.OLD, wordCount: 5637, chapters: 10 },
  { id: 'job', name: 'Job', testament: Testament.OLD, wordCount: 10102, chapters: 42 },
  { id: 'psa', name: 'Psalms', testament: Testament.OLD, wordCount: 43743, chapters: 150 },
  { id: 'pro', name: 'Proverbs', testament: Testament.OLD, wordCount: 15043, chapters: 31 },
  { id: 'ecc', name: 'Ecclesiastes', testament: Testament.OLD, wordCount: 5584, chapters: 12 },
  { id: 'sos', name: 'Song of Solomon', testament: Testament.OLD, wordCount: 2661, chapters: 8 },
  { id: 'isa', name: 'Isaiah', testament: Testament.OLD, wordCount: 37044, chapters: 66 },
  { id: 'jer', name: 'Jeremiah', testament: Testament.OLD, wordCount: 42659, chapters: 52 },
  { id: 'lam', name: 'Lamentations', testament: Testament.OLD, wordCount: 3415, chapters: 5 },
  { id: 'eze', name: 'Ezekiel', testament: Testament.OLD, wordCount: 39407, chapters: 48 },
  { id: 'dan', name: 'Daniel', testament: Testament.OLD, wordCount: 11606, chapters: 12 },
  { id: 'hos', name: 'Hosea', testament: Testament.OLD, wordCount: 5175, chapters: 14 },
  { id: 'joe', name: 'Joel', testament: Testament.OLD, wordCount: 2034, chapters: 3 },
  { id: 'amo', name: 'Amos', testament: Testament.OLD, wordCount: 4217, chapters: 9 },
  { id: 'oba', name: 'Obadiah', testament: Testament.OLD, wordCount: 670, chapters: 1 },
  { id: 'jon', name: 'Jonah', testament: Testament.OLD, wordCount: 1321, chapters: 4 },
  { id: 'mic', name: 'Micah', testament: Testament.OLD, wordCount: 3153, chapters: 7 },
  { id: 'nah', name: 'Nahum', testament: Testament.OLD, wordCount: 1285, chapters: 3 },
  { id: 'hab', name: 'Habakkuk', testament: Testament.OLD, wordCount: 1476, chapters: 3 },
  { id: 'zep', name: 'Zephaniah', testament: Testament.OLD, wordCount: 1617, chapters: 3 },
  { id: 'hag', name: 'Haggai', testament: Testament.OLD, wordCount: 1131, chapters: 2 },
  { id: 'zec', name: 'Zechariah', testament: Testament.OLD, wordCount: 6475, chapters: 14 },
  { id: 'mal', name: 'Malachi', testament: Testament.OLD, wordCount: 1782, chapters: 4 },
  { id: 'mat', name: 'Matthew', testament: Testament.NEW, wordCount: 23684, chapters: 28 },
  { id: 'mar', name: 'Mark', testament: Testament.NEW, wordCount: 15171, chapters: 16 },
  { id: 'luk', name: 'Luke', testament: Testament.NEW, wordCount: 25944, chapters: 24 },
  { id: 'joh', name: 'John', testament: Testament.NEW, wordCount: 19099, chapters: 21 },
  { id: 'act', name: 'Acts', testament: Testament.NEW, wordCount: 24250, chapters: 28 },
  { id: 'rom', name: 'Romans', testament: Testament.NEW, wordCount: 9447, chapters: 16 },
  { id: '1co', name: '1 Corinthians', testament: Testament.NEW, wordCount: 9489, chapters: 16 },
  { id: '2co', name: '2 Corinthians', testament: Testament.NEW, wordCount: 6092, chapters: 13 },
  { id: 'gal', name: 'Galatians', testament: Testament.NEW, wordCount: 3098, chapters: 6 },
  { id: 'eph', name: 'Ephesians', testament: Testament.NEW, wordCount: 3039, chapters: 6 },
  { id: 'phi', name: 'Philippians', testament: Testament.NEW, wordCount: 2202, chapters: 4 },
  { id: 'col', name: 'Colossians', testament: Testament.NEW, wordCount: 1998, chapters: 4 },
  { id: '1th', name: '1 Thessalonians', testament: Testament.NEW, wordCount: 1857, chapters: 5 },
  { id: '2th', name: '2 Thessalonians', testament: Testament.NEW, wordCount: 1042, chapters: 3 },
  { id: '1ti', name: '1 Timothy', testament: Testament.NEW, wordCount: 2269, chapters: 6 },
  { id: '2ti', name: '2 Timothy', testament: Testament.NEW, wordCount: 1703, chapters: 4 },
  { id: 'tit', name: 'Titus', testament: Testament.NEW, wordCount: 920, chapters: 3 },
  { id: 'phm', name: 'Philemon', testament: Testament.NEW, wordCount: 445, chapters: 1 },
  { id: 'heb', name: 'Hebrews', testament: Testament.NEW, wordCount: 6913, chapters: 13 },
  { id: 'jam', name: 'James', testament: Testament.NEW, wordCount: 2309, chapters: 5 },
  { id: '1pe', name: '1 Peter', testament: Testament.NEW, wordCount: 2482, chapters: 5 },
  { id: '2pe', name: '2 Peter', testament: Testament.NEW, wordCount: 1559, chapters: 3 },
  { id: '1jo', name: '1 John', testament: Testament.NEW, wordCount: 2523, chapters: 5 },
  { id: '2jo', name: '2 John', testament: Testament.NEW, wordCount: 303, chapters: 1 },
  { id: '3jo', name: '3 John', testament: Testament.NEW, wordCount: 299, chapters: 1 },
  { id: 'jud_nt', name: 'Jude', testament: Testament.NEW, wordCount: 613, chapters: 1 },
  { id: 'rev', name: 'Revelation', testament: Testament.NEW, wordCount: 12000, chapters: 22 },
];

export const TOTAL_BIBLE_WORD_COUNT = BIBLE_BOOKS.reduce((sum, book) => sum + book.wordCount, 0);
